import 'package:get/get.dart';

class LocaleString extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    'en_US':{
      'IITB Hospital':'IITB Hospital',
      'Signin as':'Signin as',
      '      Patient      ':'      Patient      ',
      '     Doctors     ':'     Doctors     ',
      '  Pharmacist  ':'  Pharmacist  ',
      'Hospital Staff':'Hospital Staff',
      'Hospital':'Hospital',
      'Doctor SignIn':'Doctor SignIn',
      'Doctor':'IITB Hospital Doctors Interface',
      'Sign out':'Sign out',
      'SignIn':'SignIn',
      'Doctors Availability':'Doctors Availability',
      'Doctors Appointment':'Doctors Appointment',
      'Pharmacy':'Pharmacy',
      'Reports':'Reports',
      'Doctors visit':'Doctors visit',
      'Reimburse':'Reimburse',
      'Medical Book':'Medical Book',
      'Lab Order':'Lab Order',
      'Student Information':'Student Information',
      'Patient SignIn':'Patient SignIn',
      'Does not have account?':'Does not have account?',
      'Sign Up':'Sign Up',
      'IITB Hospital Patients Interface':'IITB Hospital Patients Interface',
      'Enter Email Address':'Enter Email Address',
      'Call Ambulance':'Call Ambulance',
      'Dark Mode':'Dark Mode',
      'Light Mode':'Light Mode',
      'Language':'Language',
      'Contact us':'Contact us',
    },
    'hi_IN':{
      'IITB Hospital':'आईआईटीबी अस्पताल',
      'Signin as':'साइन इन करें',
      '      Patient      ':'      मरीज़      ',
      '     Doctors     ':'     डॉक्टरों     ',
      '  Pharmacist  ':'  फार्मेसिस्ट  ',
      'Hospital Staff':'हॉस्पिटल कर्मचारी',
      'Hospital':'अस्पताल',
      'Doctor SignIn':'डॉक्टर साइन इन',
      'Doctor':'आईआईटीबी अस्पताल के डॉक्टर इंटरफेस',
      'Sign out':'साइन आउट',
      'SignIn':'साइन इन करें',
      'Doctors Availability':'डॉक्टरों की उपलब्धता',
      'Doctors Appointment':'डॉक्टरों की नियुक्ति',
      'Pharmacy':'औषधशाला',
      'Reports':'रिपोर्ट',
      'Doctors visit':'डॉक्टरों ने किया दौरा',
      'Reimburse':'प्रतिपूर्ति',
      'Medical Book':'मेडिकल बुक',
      'Lab Order':'लैब का ऑर्डर',
      'Student Information':'विद्यार्थी की जानकारी',
      'Patient SignIn':'रोगी साइन इन करें',
      'Does not have account?':'क्या आपका कोई हिसाब नहीं है?',
      'Sign Up':'नाम लिखो',
      'IITB Hospital Patients Interface':'आईआईटीबी अस्पताल के मरीजों का इंटरफेस',
      'Enter Email Address':'ईमेल पता दर्ज करें',
      'Call Ambulance':'कॉल एम्बुलेंस',
      'Dark Mode':'डार्क मोड',
      'Light Mode':'लाइट मोड',
      'Language':'भाषा',
      'Contact us':'संपर्क करें',
    },
    'kn_IN':{
      'IITB Hospital':'ಐಐಟಿಬಿ ಆಸ್ಪತ್ರೆ',
      'Signin as':'ಹೀಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
      '      Patient      ':'      ರೋಗಿ      ',
      '     Doctors     ':'     ವೈದ್ಯರು     ',
      '  Pharmacist  ':'  ಫಾರ್ಮಾಸಿಸ್ಟ್  ',
      'Hospital Staff':'ಆಸ್ಪತ್ರೆ ಸಿಬ್ಬಂದಿ',
      'Hospital':'ಆಸ್ಪತ್ರೆ',
      'Doctor SignIn':'ಡಾಕ್ಟರ್ ಸೈನ್ ಇನ್',
      'Doctor':'ಐಐಟಿಬಿ ಆಸ್ಪತ್ರೆ ವೈದ್ಯರ ಇಂಟರ್ಫೇಸ್',
      'Sign out':'ಸೈನ್ ಔಟ್ ಮಾಡಿ',
      'SignIn':'ಸೈನ್ ಇನ್',
      'Doctors Availability':'ವೈದ್ಯರ ಲಭ್ಯತೆ',
      'Doctors Appointment':'ವೈದ್ಯರ ಅಪಾಯಿಂಟ್ಮೆಂಟ್',
      'Pharmacy':'ಫಾರ್ಮಸಿ',
      'Reports':'ವರದಿಗಳು',
      'Doctors visit':'ವೈದ್ಯರ ಭೇಟಿ',
      'Reimburse':'ಮರುಪಾವತಿ ಮಾಡಿ',
      'Medical Book':'ವೈದ್ಯಕೀಯ ಪುಸ್ತಕ',
      'Lab Order':'ಲ್ಯಾಬ್ ಆರ್ಡರ್',
      'Student Information':'ವಿದ್ಯಾರ್ಥಿ ಮಾಹಿತಿ',
      'Patient SignIn':'ರೋಗಿ ಸೈನ್ ಇನ್',
      'Does not have account?':'ಖಾತೆ ಹೊಂದಿಲ್ಲವೇ?',
      'Sign Up':'ಸೈನ್ ಅಪ್ ಮಾಡಿ',
      'IITB Hospital Patients Interface':'ಐಐಟಿಬಿ ಆಸ್ಪತ್ರೆ ರೋಗಿಗಳ ಇಂಟರ್ಫೇಸ್',
      'Enter Email Address':'ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ',
      'Call Ambulance':'ಆಂಬ್ಯುಲೆನ್ಸ್‌ಗೆ ಕರೆ ಮಾಡಿ',
      'Dark Mode':'ಡಾರ್ಕ್ ಮೋಡ್',
      'Light Mode':'ಲೈಟ್ ಮೋಡ್',
      'Language':'ಭಾಷೆ',
      'Contact us':'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    },
    'te_IN':{
      'IITB Hospital':'ఐఐటిబి హాస్పిటల్',
      'Signin as':'ఇలా సైన్ ఇన్ చేయండి',
      '      Patient      ':' రోగులు ',
      '     Doctors     ':'వైద్యులు',
      '  Pharmacist  ':'ఫార్మసిస్ట',
      'Hospital Staff':'ఆసుపత్రి సిబ్బంది',
      'Hospital':'ఆసుపత్రి',
      'Doctor SignIn':'డాక్టర్ సైన్ ఇన్',
      'Doctor':'ఐఐటిబి హాస్పిటల్ డాక్టర్స్ ఇంటర్‌ఫేస్',
      'Sign out':'సైన్ అవుట్',
      'SignIn':'సైన్ ఇన్',
      'Doctors Availability':'వైద్యుల లభ్యత',
      'Doctors Appointment':'డాక్టర్ల నియామకం',
      'Pharmacy':'ఔషధశాల',
      'Reports':'రిపోర్టులు',
      'Doctors visit':'వైద్యుల సందర్శన',
      'Reimburse':'రీఎంబర్స్',
      'Medical Book':'మెడికల్ బుక్',
      'Lab Order':'ల్యాబ్ ఆర్డర్',
      'Student Information':'విద్యార్థి సమాచారం',
      'Patient SignIn':'రోగి సైన్ ఇన్',
      'Does not have account?':'ఖాతా లేదా?',
      'Sign Up':'సైన్ అప్',
      'IITB Hospital Patients Interface':'ఐఐటిబి హాస్పిటల్ పేషెంట్స్ ఇంటర్ ఫేస్',
      'Enter Email Address':'ఈ - మెయిల్ అడ్రస్ నింపండి',
      'Call Ambulance':'అంబులెన్స్‌కి కాల్ చేయండి',
      'Dark Mode':'డార్క్ మోడ్',
      'Light Mode':'లైట్ మోడ్',
      'Language':'భాష',
      'Contact us':'మమ్మల్ని సంప్రదించండి',
    },
  };

}
